name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Building and Testing
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            echo "Lock file found — running npm ci"
            npm ci
          else
            echo "No lock file found — running npm install"
            npm install
          fi

      # Step 4: Run lint if script exists
      - name: Lint (if available)
        run: |
          if npm run | grep -q "lint"; then
            npm run lint --silent
          else
            echo "No lint script found in package.json — skipping lint."
          fi

      # Step 5: Run tests if script exists
      - name: Run tests (if available)
        run: |
          if npm run | grep -q "test"; then
            npm test --silent || ( echo "Tests failed"; exit 1 )
          else
            echo "No test script found in package.json — skipping tests."
          fi
